# Generated by Django 6.0.3 on 2026-05-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsevent',
            name='action',
            field=models.CharField(choices=[('git_pull', 'Git Pull'), ('git_status', 'Git Status'), ('git_log', 'Git Log'), ('git_diff', 'Git Diff'), ('collectstatic', 'Collect Static'), ('sync_genre_wiki', 'Sync Genre Wiki'), ('reload', 'Gunicorn Reload'), ('ticket_create', 'Ticket Created'), ('other', 'Other')], max_length=40),
        ),
    ]
