# Generated by Django 5.2.13 on 2026-05-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='Internal or external link for this project', max_length=500),
        ),
    ]
