# Generated by Django 5.2.13 on 2026-05-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_hosted_domain_alter_client_id_and_more'),
        ('projects', '0002_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='clients.client'),
        ),
    ]
