# Generated by Django 5.2.13 on 2026-05-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, choices=[('poc', 'Proof of Concept'), ('development', 'Development'), ('maintaining', 'Maintaining')], default='', max_length=20),
        ),
    ]
