# Generated by Django 5.2.13 on 2026-05-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_visible',
            field=models.BooleanField(default=False),
        ),
    ]
