# Generated by Django 5.2.13 on 2026-06-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_task_client_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='entity',
            field=models.CharField(choices=[('binsky', 'Binsky'), ('fckry', 'FCKRY LLC'), ('community', 'Community Playlist'), ('clients', 'Clients'), ('general', 'General')], db_index=True, default='general', max_length=20),
        ),
    ]
