# Generated by Django 5.2.13 on 2026-06-11 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_contact_portal_fields'),
        ('projects', '0007_dashboard_app_and_project_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_contact',
            field=models.ForeignKey(blank=True, help_text='Client-side contact this task is assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='clients.contact'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to_user',
            field=models.ForeignKey(blank=True, help_text='Staff/contractor this task is assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
