# Generated by Django 5.2.15 on 2026-06-11 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_ai', '0002_memorynote'),
        ('projects', '0008_task_assigned_to_contact_task_assigned_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, help_text="Attribute this conversation's token spend to a project for cost tracking.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='projects.project'),
        ),
    ]
