# Generated by Django 5.2.13 on 2026-06-05 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gitnode', '0002_alter_managedrepo_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HihiModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('github_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('github_name', models.CharField(blank=True, max_length=200)),
                ('github_url', models.URLField(blank=True)),
                ('github_desc', models.TextField(blank=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('topics', models.JSONField(default=list)),
                ('stars', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module_type', models.CharField(choices=[('ai', 'AI / ML'), ('web', 'Web App'), ('cp', 'Community Playlist'), ('infra', 'Infrastructure'), ('utility', 'Utility'), ('tool', 'Tool / CLI')], default='web', max_length=20)),
                ('status', models.CharField(choices=[('live', 'Live'), ('beta', 'Beta'), ('wip', 'WIP'), ('archived', 'Archived')], default='wip', max_length=20)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(default='fa-code', max_length=60)),
                ('icon_class', models.CharField(default='fa-solid', max_length=20)),
                ('color', models.CharField(default='#7c6af7', max_length=7)),
                ('live_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('fleet_service', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Show on public Works page')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managed_repo', models.OneToOneField(blank=True, help_text='Linked deploy repo — enables git status / scoop / deploy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module', to='gitnode.managedrepo')),
            ],
            options={
                'ordering': ['module_type', 'name'],
            },
        ),
    ]
