# Generated by Django 5.2.15 on 2026-06-12 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_hihimodule_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cloning', 'Cloning'), ('building', 'Building'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='cloning', max_length=10)),
                ('container', models.CharField(blank=True, max_length=120)),
                ('port', models.PositiveIntegerField(default=0)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='modules.hihimodule')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_instances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
