# Generated by Django 5.2.13 on 2026-05-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clients', '0005_alter_client_hosted_domain_alter_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.client'),
        ),
    ]
