# Generated by Django 5.2.15 on 2026-06-11 04:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_client_fk'),
        ('projects', '0008_task_assigned_to_contact_task_assigned_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_cost_per_hour', models.DecimalField(decimal_places=2, default=40, help_text='What an hour of work actually costs you (not the client bill rate).', max_digits=8)),
                ('ai_cost_per_1k_tokens', models.DecimalField(decimal_places=4, default=0.01, help_text='Blended $ per 1k tokens across the AI stack.', max_digits=8)),
                ('overhead_monthly', models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly overhead: hosting, electricity, software subs, accounting…', max_digits=10)),
                ('target_margin_pct', models.DecimalField(decimal_places=2, default=150, help_text='Markup over cost floor, in percent (150 = price at 2.5x cost).', max_digits=6)),
                ('default_client_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Pricing multiplier used when a client has no pricing_factor set.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cost settings',
                'verbose_name_plural': 'Cost settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly recurring')], default='one_time', max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
