# Generated by Django 5.2.13 on 2026-06-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_costsettings_projectexpense'),
        ('billing', '0003_drop_orphan_payment_url'),
    ]

    operations = [
    ]
