# Generated by Django 5.2.13 on 2026-05-27 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_client_fk'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-wrench', help_text='FontAwesome icon class', max_length=60)),
                ('color', models.CharField(default='#7c6af7', max_length=7)),
                ('recurrence', models.CharField(choices=[('one-time', 'One-time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('day_of_month', models.IntegerField(default=1, help_text='For monthly: day to trigger (1-28)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_services', to='projects.project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_services', to='services.service')),
            ],
            options={
                'unique_together': {('project', 'service')},
            },
        ),
    ]
