# Generated by Django 5.2.15 on 2026-06-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectservice',
            name='monthly_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What providing this service for this project costs you per month.', max_digits=8),
        ),
    ]
