# Generated by Django 5.2.14 on 2026-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitnode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedrepo',
            name='path',
            field=models.CharField(help_text='Absolute path on the server, e.g. /var/www/vhosts/danklean.com/django', max_length=500),
        ),
        migrations.AlterField(
            model_name='managedrepo',
            name='service_name',
            field=models.CharField(blank=True, help_text='systemd service to restart after deploy, e.g. danklean', max_length=100),
        ),
    ]
