# Generated by Django 5.2.13 on 2026-05-28 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_alter_client_hosted_domain_alter_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_type', models.CharField(choices=[('public', 'Public Site'), ('portal', 'Client Portal')], max_length=10, unique=True)),
                ('html_content', models.TextField(blank=True, help_text='HTML injected into the footer.')),
                ('show_ticket_form', models.BooleanField(default=False)),
                ('ticket_form_title', models.CharField(default='Submit a Ticket', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_projects', models.BooleanField(default=True)),
                ('show_invoices', models.BooleanField(default=True)),
                ('show_files', models.BooleanField(default=True)),
                ('show_tickets', models.BooleanField(default=True)),
                ('show_messages', models.BooleanField(default=False)),
                ('welcome_message', models.TextField(blank=True)),
                ('accent_color', models.CharField(default='#7c6af7', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_config', to='clients.client')),
            ],
        ),
    ]
