# Generated by Django 5.2.13 on 2026-05-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='icon',
            field=models.CharField(choices=[('fa-server', 'Server'), ('fa-cloud', 'Cloud'), ('fa-database', 'Database'), ('fa-docker', 'Docker'), ('fa-linux', 'Linux'), ('fa-raspberry-pi', 'Pi'), ('fa-network-wired', 'Network'), ('fa-shield', 'VPN / Secure')], default='fa-server', max_length=40),
        ),
    ]
