# Generated by Django 5.2.15 on 2026-06-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_task_assigned_to_contact_task_assigned_to_user'),
        ('servers', '0002_alter_server_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='monthly_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What this server costs per month (hosting bill, amortized hardware + power).', max_digits=8),
        ),
        migrations.AddField(
            model_name='server',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this server supports — its monthly cost is split evenly across them.', related_name='servers', to='projects.project'),
        ),
    ]
