# Generated by Django 5.2.13 on 2026-06-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_server_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['platform', 'name']},
        ),
        migrations.AddField(
            model_name='server',
            name='domain',
            field=models.URLField(blank=True, help_text='Public URL, e.g. https://hihilabs.xyz'),
        ),
        migrations.AddField(
            model_name='server',
            name='git_repo',
            field=models.URLField(blank=True, help_text='GitHub repo URL'),
        ),
        migrations.AddField(
            model_name='server',
            name='platform',
            field=models.CharField(choices=[('vps', 'VPS'), ('docker', 'Docker / VPS'), ('unraid', 'Unraid'), ('external', 'External'), ('local', 'Local')], default='vps', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='service_type',
            field=models.CharField(choices=[('django', 'Django'), ('node', 'Node.js'), ('nginx', 'Static / nginx'), ('docker', 'Docker app'), ('ssh', 'SSH server'), ('other', 'Other')], default='ssh', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='status_url',
            field=models.URLField(blank=True, help_text='Health-check URL (HTTP 2xx = up)'),
        ),
    ]
