# Generated by Django 5.2.13 on 2026-06-04 20:44

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_alter_server_options_server_domain_server_git_repo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='domain',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='git_repo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='status_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('work_email', models.EmailField(blank=True, help_text='e.g. quinn@hihilabs.xyz', max_length=254)),
                ('github_login', models.CharField(blank=True, max_length=100)),
                ('linux_user', models.CharField(blank=True, help_text='Linux username on VPS', max_length=64)),
                ('color', models.CharField(default='#7c6af7', max_length=7)),
                ('avatar_emoji', models.CharField(default='👤', max_length=8)),
                ('ssh_key_fingerprints', models.TextField(blank=True, help_text='One SHA256 fingerprint per line — used to identify device on login')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('task_summary', models.TextField(blank=True, help_text='What are you working on?')),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('checked_out', 'Checked out')], default='active', max_length=20)),
                ('ssh_fingerprint', models.CharField(blank=True, max_length=200)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client_hostname', models.CharField(blank=True, max_length=200)),
                ('session_token', models.CharField(default=secrets.token_hex, max_length=64)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='servers.developer')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='servers.server')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
