# Generated by Django 5.2.13 on 2026-06-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_monthly_cost_server_projects'),
        ('servers', '0004_alter_server_domain_alter_server_git_repo_and_more'),
    ]

    operations = [
    ]
