# Generated by Django 5.2.13 on 2026-05-14 19:55

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('api_key', models.CharField(default=secrets.token_hex, max_length=64, unique=True)),
                ('color', models.CharField(default='#7c6af7', max_length=7)),
                ('gpu_priority', models.IntegerField(default=50, help_text='0–100; higher = more GPU time')),
                ('api_priority', models.IntegerField(default=50, help_text='0–100; higher = more Claude API quota')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-gpu_priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('requires_gpu', models.BooleanField(default=False)),
                ('requires_claude', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='WorkerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('worker_type', models.CharField(choices=[('pull', 'Pull Worker'), ('ocr', 'OCR Server'), ('labeler', 'Labeler'), ('hybrid', 'Hybrid')], default='pull', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('gpu', models.CharField(blank=True, max_length=100)),
                ('capabilities', models.JSONField(default=list)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('cpu_pct', models.FloatField(blank=True, null=True)),
                ('mem_pct', models.FloatField(blank=True, null=True)),
                ('vram_used', models.IntegerField(blank=True, null=True)),
                ('vram_total', models.IntegerField(blank=True, null=True)),
                ('active_jobs', models.IntegerField(default=0)),
                ('current_job', models.JSONField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('secret_key', models.CharField(default=secrets.token_hex, max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (5, 'Normal'), (10, 'High'), (20, 'Urgent')], default=5)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='queued', max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('progress', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workers.client')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.jobtype')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.workernode')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
