# Generated by Django 5.2.13 on 2026-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workernode',
            name='pending_command',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
