# Generated by Django 5.2.15 on 2026-06-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_add_pending_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workernode',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
