# Module registry — add new modules here, no migrations needed.
# type:    'ai' | 'web' | 'cp' | 'infra' | 'utility'
# status:  'live' | 'beta' | 'wip'
# platform: free text — 'Web', 'Unraid Docker', 'Unraid / Plex', 'Android', etc.
# icon_class: FA prefix — defaults to 'fa-solid'; use 'fa-brands' for brand icons
# fleet_service: Server.name from the Fleet registry — links module → infrastructure

MODULES = [

    # ── AI ────────────────────────────────────────────────────────────────────

    {
        'slug':        'hihilabs',
        'name':        'HiHi Labs',
        'type':        'ai',
        'icon':        'fa-flask',
        'color':       '#7c6af7',
        'description': 'This platform. Personal business OS — AI chat with tool use and slash commands, projects, billing, servers, voice notes, document templates. Self-modifying via Claude.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://hihilabs.xyz',
        'source_url':  'https://github.com/khildren/hihi.labs',
        'tags':        ['django', 'claude', 'ai', 'docker'],
        'fleet_service': 'HiHi Labs CRM',
    },
    {
        'slug':        'camagent',
        'name':        'CamAgent',
        'type':        'ai',
        'icon':        'fa-camera',
        'color':       '#4fffb0',
        'description': 'HVAC nameplate OCR pipeline. CompanyCam photos → detect nameplate → EasyOCR / Tesseract / LLaVA → parse model/serial/brand/tonnage/refrigerant → export CSV/JSON/XLSX. Dual Quadro GPU workers on Unraid.',
        'status':      'live',
        'platform':    'Unraid GPU',
        'live_url':    'https://agent.omegamep.com',
        'source_url':  'https://github.com/khildren/camagent',
        'tags':        ['ocr', 'ai', 'gpu', 'unraid', 'hvac', 'django'],
        'fleet_service': 'OmegaMEP / HiHi',
    },

    # ── Web Apps ──────────────────────────────────────────────────────────────

    {
        'slug':        'hihi-omegamep',
        'name':        'HiHi OmegaMEP',
        'type':        'web',
        'icon':        'fa-helmet-safety',
        'color':       '#818cf8',
        'description': 'Field service CRM for OmegaMEP HVAC. Dispatch board, jobs, assets, contacts, invoicing, timesheets, KB, calendar — role-based dashboards for godmode / dispatch / field / customer.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://hihi.omegamep.com',
        'source_url':  'https://github.com/khildren/hihi',
        'tags':        ['django', 'crm', 'hvac', 'docker', 'pwa'],
        'fleet_service': 'OmegaMEP / HiHi',
    },
    {
        'slug':        'communityplaylist',
        'name':        'CommunityPlaylist',
        'type':        'web',
        'icon':        'fa-record-vinyl',
        'color':       '#f97316',
        'description': 'PDX music discovery and community platform. Event listings, artist/crew profiles, social pipeline, genre wiki, audio player, flyer maker, record shop, Discord sync, and mutual aid tools — all in one Django monorepo.',
        'status':      'live',
        'platform':    'Web + Unraid Docker',
        'live_url':    'https://communityplaylist.com',
        'source_url':  'https://github.com/khildren/communityplaylist',
        'tags':        ['django', 'music', 'social', 'platform', 'pwa'],
        'fleet_service': 'Community Playlist',
    },

    # ── Community Playlist — Feature Modules ─────────────────────────────────

    {
        'slug':        'cp-events',
        'name':        'CP · Events',
        'type':        'cp',
        'icon':        'fa-calendar-days',
        'color':       '#f97316',
        'description': 'Core event discovery engine. List / Map / Hybrid three-way view with localStorage persistence, GPS-to-nearest-event scroll, Leaflet map, and event card rendering.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://communityplaylist.com/events/',
        'source_url':  'https://github.com/hihilabs/cp-events',
        'tags':        ['leaflet', 'map', 'hybrid-view', 'gps', 'django'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-player',
        'name':        'CP · Player',
        'type':        'cp',
        'icon':        'fa-circle-play',
        'color':       '#f97316',
        'description': 'Floating audio player panel + standalone player page. Shuffle with Fisher-Yates, repeat modes, localStorage persistence, Plex/YouTube embed support, queue management, keyboard controls.',
        'status':      'live',
        'platform':    'Web → PWA → Mobile',
        'live_url':    'https://communityplaylist.com/events/player/',
        'source_url':  'https://github.com/hihilabs/cp-player',
        'tags':        ['audio', 'plex', 'youtube', 'shuffle', 'queue', 'pwa'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-flyer',
        'name':        'CP · Flyer Maker',
        'type':        'cp',
        'icon':        'fa-image',
        'color':       '#f97316',
        'description': 'In-browser event flyer generator. Portrait + Square formats, drag-and-drop background picker, 8 gradient art presets, user uploads, Download PNG via html2canvas, Bluesky intent share.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://communityplaylist.com/events/example/flyer/',
        'source_url':  'https://github.com/hihilabs/cp-flyer',
        'tags':        ['pil', 'html2canvas', 'social', 'bluesky', 'instagram'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-social',
        'name':        'CP · Social Pipeline',
        'type':        'cp',
        'icon':        'fa-share-nodes',
        'color':       '#f97316',
        'description': 'Automated social blast pipeline. Buffer (Instagram/Threads/Facebook), Bluesky rich-text facets, Discord embeds. PIL-generated 1080×1080 PNG carousel cards. Genre hashtag slugifier.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/hihilabs/cp-social',
        'tags':        ['buffer', 'bluesky', 'discord', 'pil', 'instagram', 'automation'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-wiki',
        'name':        'CP · Genre Wiki',
        'type':        'cp',
        'icon':        'fa-diagram-project',
        'color':       '#f97316',
        'description': 'Atomic genre token taxonomy. D3.js force-directed graph with cinema drift and crossfade morphing. Tokens synced from edit.music co-occurrence API. MusicBrainz/Last.fm/Discogs cross-reference enrichment.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://wiki.communityplaylist.com',
        'source_url':  'https://github.com/hihilabs/cp-wiki',
        'tags':        ['d3', 'graph', 'taxonomy', 'musicbrainz', 'django-app'],
        'fleet_service': 'Genre Wiki',
    },
    {
        'slug':        'cp-artists',
        'name':        'CP · Artist & Crew Profiles',
        'type':        'cp',
        'icon':        'fa-compact-disc',
        'color':       '#f97316',
        'description': 'Artist and PromoterProfile pages. Crew / Sound System / Collective / Record Label / Record Swap types. Social handles, bio, genre tags. Record shop with vinyl listings, payment options.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://communityplaylist.com/promoters/',
        'source_url':  'https://github.com/hihilabs/cp-artists',
        'tags':        ['profiles', 'vinyl', 'record-shop', 'solana'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-board',
        'name':        'CP · Community Board',
        'type':        'cp',
        'icon':        'fa-comments',
        'color':       '#f97316',
        'description': 'Community discussion board. Topics, Q&A, announcements, free & trade offers. Posts blast to Bluesky + Discord on approval. Neighborhood tagging, image attachments, moderation queue.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://communityplaylist.com/board/',
        'source_url':  'https://github.com/hihilabs/cp-board',
        'tags':        ['community', 'forum', 'bluesky', 'discord', 'moderation'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-discord',
        'name':        'CP · Discord Sync',
        'type':        'cp',
        'icon':        'fa-discord',
        'icon_class':  'fa-brands',
        'color':       '#f97316',
        'description': 'Bi-directional Discord integration. Approved events → rich embeds in #events. sync_discord_events harvests Discord scheduled events into CP. Board topics and free trade items blast to channels.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/hihilabs/cp-discord',
        'tags':        ['discord', 'webhooks', 'sync', 'automation'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-ops',
        'name':        'CP · Ops Panel',
        'type':        'cp',
        'icon':        'fa-gauge-high',
        'color':       '#f97316',
        'description': 'Staff-only ops dashboard. Git status/pull/log/diff, collectstatic, gunicorn reload via SIGHUP, sync_genre_wiki trigger. Ticket tracker with priority, audit log. Drop-in Django app.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://communityplaylist.com/ops/',
        'source_url':  'https://github.com/hihilabs/cp-ops',
        'tags':        ['django-app', 'ops', 'deploy', 'tickets', 'staff-only'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-video',
        'name':        'CP · Video Harvesting',
        'type':        'cp',
        'icon':        'fa-film',
        'color':       '#f97316',
        'description': 'YouTube and Twitch VOD harvesting for linked artist/venue channels. VideoTrack model with source type, channel ID, and profile link. Embedded playback on profile pages.',
        'status':      'beta',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/hihilabs/cp-video',
        'tags':        ['youtube', 'twitch', 'video', 'embed'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-genres',
        'name':        'CP · Genre Sync',
        'type':        'cp',
        'icon':        'fa-tags',
        'color':       '#f97316',
        'description': 'Genre taxonomy pipeline. Pulls co-occurrence data from edit.music API, splits tags into atomic tokens (protected phrases: R&B, Lo-Fi, G-Funk), builds GenreToken and CompoundGenre records, wires related-genre edges.',
        'status':      'live',
        'platform':    'Unraid Docker',
        'live_url':    '',
        'source_url':  'https://github.com/hihilabs/cp-genres',
        'tags':        ['genres', 'taxonomy', 'edit-music', 'management-command'],
        'fleet_service': 'Genre Wiki',
    },
    {
        'slug':        'cp-spaces',
        'name':        'CP · Community Spaces',
        'type':        'cp',
        'icon':        'fa-tree',
        'color':       '#f97316',
        'description': 'Community spaces directory — gardens, parks, mutual aid hubs, and gathering spots. Space updates feed, photo gallery, Ko-fi integration, and CommunityAsk board for resource requests.',
        'status':      'beta',
        'platform':    'Web',
        'live_url':    'https://communityplaylist.com/spaces/',
        'source_url':  'https://github.com/hihilabs/cp-spaces',
        'tags':        ['mutual-aid', 'community', 'spaces', 'kofi'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-shelter',
        'name':        'CP · Shelter Listings',
        'type':        'cp',
        'icon':        'fa-house',
        'color':       '#f97316',
        'description': 'Emergency and transitional shelter listings with availability tracking, service flags (pets, families, LGBTQ+, gender-specific), capacity, and contact info. Part of CP\'s mutual aid toolkit.',
        'status':      'beta',
        'platform':    'Web',
        'live_url':    'https://communityplaylist.com/shelter/',
        'source_url':  'https://github.com/hihilabs/cp-shelter',
        'tags':        ['mutual-aid', 'shelter', 'housing', 'community'],
        'fleet_service': 'Community Playlist',
    },
    {
        'slug':        'cp-labeler',
        'name':        'CP · Music Labeler',
        'type':        'cp',
        'icon':        'fa-tag',
        'color':       '#f97316',
        'description': 'edit.music PWA — mobile music file tagger running on Unraid. Lidarr-Tidal sync bridge polls Lidarr wanted list and queues LOSSLESS downloads via TidaLoader. Genre co-occurrence data feeds the CP Genre Wiki.',
        'status':      'live',
        'platform':    'Unraid Docker',
        'live_url':    'http://10.0.0.124:8090',
        'source_url':  'https://github.com/khildren/edit.music',
        'tags':        ['pwa', 'music-tagging', 'lidarr', 'tidal', 'unraid'],
        'fleet_service': 'edit.music',
    },
    {
        'slug':        'lostsignal',
        'name':        'Lost Signal',
        'type':        'web',
        'icon':        'fa-tower-broadcast',
        'color':       '#e879f9',
        'description': 'Music label and artist platform.',
        'status':      'wip',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/lostsignal',
        'tags':        ['music', 'label'],
        'fleet_service': 'Lost Signal',
    },
    {
        'slug':        'apothecary',
        'name':        'Apothecary',
        'type':        'web',
        'icon':        'fa-mortar-pestle',
        'color':       '#34d399',
        'description': '',
        'status':      'wip',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/apothecary',
        'tags':        [],
        'fleet_service': 'VPS (panel)',
    },
    {
        'slug':        'bluesolutions',
        'name':        'Blue Solutions',
        'type':        'web',
        'icon':        'fa-droplet',
        'color':       '#38bdf8',
        'description': 'Blue Solutions business site.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://bluesolutions.biz',
        'source_url':  'https://github.com/khildren/bluesolutions',
        'tags':        ['wordpress', 'business'],
        'fleet_service': 'VPS (panel)',
    },
    {
        'slug':        'epk',
        'name':        'EPK',
        'type':        'web',
        'icon':        'fa-id-card',
        'color':       '#a78bfa',
        'description': 'Electronic Press Kit.',
        'status':      'wip',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/epk',
        'tags':        ['music', 'press', 'portfolio'],
        'fleet_service': 'FAC / EPK',
    },
    {
        'slug':        'portfolio-blue',
        'name':        'Portfolio Blue',
        'type':        'web',
        'icon':        'fa-briefcase',
        'color':       '#60a5fa',
        'description': 'Portfolio site.',
        'status':      'wip',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/portfolio-blue',
        'tags':        ['portfolio'],
        'fleet_service': 'VPS (panel)',
    },
    {
        'slug':        'seedling-society',
        'name':        'Seedling Society',
        'type':        'web',
        'icon':        'fa-seedling',
        'color':       '#86efac',
        'description': 'Seedling Society marketplace and community platform.',
        'status':      'wip',
        'platform':    'Web',
        'live_url':    'https://seedlingsociety.com',
        'source_url':  'https://github.com/khildren/seedling-society-market',
        'tags':        ['marketplace', 'community', 'e-commerce'],
        'fleet_service': 'Seedling Society',
    },

    # ── HiHi Node ─────────────────────────────────────────────────────────────

    {
        'slug':        'hihi-node',
        'name':        'HiHi Node',
        'type':        'infra',
        'icon':        'fa-code-branch',
        'color':       '#4ade80',
        'description': 'Git operations dashboard for all managed VPS repos. Live status, commit diff, scoop (stage → commit → push) per-repo or all at once. SSH into each server at deploy time. Replaces manual `scoop` shell workflow.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://hihilabs.xyz/gitnode/',
        'source_url':  'https://github.com/khildren/hihi.labs',
        'tags':        ['git', 'deploy', 'ssh', 'ops', 'vps'],
        'fleet_service': 'HiHi Labs CRM',
    },

    # ── Infra / Tools ─────────────────────────────────────────────────────────

    {
        'slug':        'sapiens',
        'name':        'Sapiens Server',
        'type':        'infra',
        'icon':        'fa-city',
        'color':       '#fbbf24',
        'description': 'Sapiens city-builder game server in Docker on Unraid. Custom container from the official Linux build — template for hosting indie game servers for small businesses, families, or community groups.',
        'status':      'live',
        'platform':    'Unraid Docker',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/docker-sapiens',
        'tags':        ['docker', 'game', 'unraid', 'small-biz', 'template'],
        'fleet_service': 'Unraid NAS',
    },
    {
        'slug':        'lidarr-mv-sync',
        'name':        'Lidarr MV Sync',
        'type':        'infra',
        'icon':        'fa-film',
        'color':       '#f472b6',
        'description': 'Syncs Lidarr music library with music video files. Watches for new Lidarr downloads and auto-organizes music video counterparts into Plex-compatible folders.',
        'status':      'live',
        'platform':    'Unraid / Plex',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/mv-lidarr-addon',
        'tags':        ['plex', 'lidarr', 'unraid', 'music', 'automation'],
        'fleet_service': 'Unraid NAS',
    },
    {
        'slug':        'cp-worker',
        'name':        'CP Worker',
        'type':        'infra',
        'icon':        'fa-gears',
        'color':       '#f97316',
        'description': 'CommunityPlaylist background worker. Handles async processing jobs for the CP platform. Runs as a Docker container on Unraid.',
        'status':      'live',
        'platform':    'Unraid Docker',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/cp-worker',
        'tags':        ['docker', 'unraid', 'worker', 'communityplaylist'],
        'fleet_service': 'Unraid NAS',
    },
    {
        'slug':        'tokyo7-admin-api',
        'name':        'Tokyo7 Admin API',
        'type':        'infra',
        'icon':        'fa-server',
        'color':       '#2dd4bf',
        'description': 'Admin and automation API for the Tokyo7 server infrastructure. Handles remote management tasks and scripted operations.',
        'status':      'live',
        'platform':    'Unraid',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/tokyo7-admin-api',
        'tags':        ['api', 'admin', 'unraid', 'server', 'automation'],
        'fleet_service': 'Unraid NAS',
    },

    # ── Utility / Bots ────────────────────────────────────────────────────────

    {
        'slug':        'discord-bot',
        'name':        'Discord Bot',
        'type':        'utility',
        'icon':        'fa-robot',
        'color':       '#818cf8',
        'description': 'Discord bot running in Docker on Unraid.',
        'status':      'live',
        'platform':    'Unraid Docker',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/discord-bot',
        'tags':        ['discord', 'bot', 'docker', 'unraid'],
        'fleet_service': 'Unraid NAS',
    },
    {
        'slug':        'tokyo7-discord-bot',
        'name':        'Tokyo7 Discord Bot',
        'type':        'utility',
        'icon':        'fa-robot',
        'color':       '#2dd4bf',
        'description': 'Discord bot for the Tokyo7 server community.',
        'status':      'live',
        'platform':    'Unraid',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/tokyo7-discord-bot',
        'tags':        ['discord', 'bot', 'tokyo7'],
        'fleet_service': 'Unraid NAS',
    },
    {
        'slug':        'sms-autoreplier',
        'name':        'SMS AutoReplier',
        'type':        'utility',
        'icon':        'fa-comment-dots',
        'color':       '#7c6af7',
        'description': 'Native Android background service — watches incoming SMS for keyword patterns and fires a configurable auto-reply in milliseconds. Built for on-call shift claiming.',
        'status':      'beta',
        'platform':    'Android',
        'live_url':    'https://expo.hihilabs.xyz',
        'source_url':  'https://expo.hihilabs.xyz/sms-autoreplier-src.tar',
        'tags':        ['android', 'kotlin', 'sms', 'automation'],
        'fleet_service': '',
    },
]
