# Module registry — add new modules here, no migrations needed.
# type:    'ai' | 'web' | 'infra' | 'utility'
# status:  'live' | 'beta' | 'wip'
# platform: free text — 'Web', 'Unraid Docker', 'Unraid / Plex', 'Android', etc.

MODULES = [

    # ── AI ────────────────────────────────────────────────────────────────────

    {
        'slug':        'hihilabs',
        'name':        'HiHi Labs',
        'type':        'ai',
        'icon':        'fa-flask',
        'color':       '#7c6af7',
        'description': 'This platform. Personal business OS — AI chat with tool use and slash commands, projects, billing, servers, voice notes, document templates. Self-modifying via Claude.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://hihilabs.xyz',
        'source_url':  'https://github.com/khildren/hihi.labs',
        'tags':        ['django', 'claude', 'ai', 'docker'],
    },
    {
        'slug':        'camagent',
        'name':        'CamAgent',
        'type':        'ai',
        'icon':        'fa-camera-viewfinder',
        'color':       '#4fffb0',
        'description': 'HVAC nameplate OCR pipeline. CompanyCam photos → detect nameplate → EasyOCR / Tesseract / LLaVA → parse model/serial/brand/tonnage/refrigerant → export CSV/JSON/XLSX. Dual Quadro GPU workers on Unraid.',
        'status':      'live',
        'platform':    'Unraid GPU',
        'live_url':    'https://agent.omegamep.com',
        'source_url':  'https://github.com/khildren/camagent',
        'tags':        ['ocr', 'ai', 'gpu', 'unraid', 'hvac', 'django'],
    },

    # ── Web Apps ──────────────────────────────────────────────────────────────

    {
        'slug':        'hihi-omegamep',
        'name':        'HiHi OmegaMEP',
        'type':        'web',
        'icon':        'fa-helmet-safety',
        'color':       '#818cf8',
        'description': 'Field service CRM for OmegaMEP HVAC. Dispatch board, jobs, assets, contacts, invoicing, timesheets, KB, calendar — role-based dashboards for godmode / dispatch / field / customer.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://hihi.omegamep.com',
        'source_url':  'https://github.com/khildren/hihi',
        'tags':        ['django', 'crm', 'hvac', 'docker', 'pwa'],
    },
    {
        'slug':        'communityplaylist',
        'name':        'CommunityPlaylist',
        'type':        'web',
        'icon':        'fa-record-vinyl',
        'color':       '#f97316',
        'description': 'Music discovery and community playlist platform. Artist pages, social curation, playlists, and music tools for labels and fans.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://communityplaylist.com',
        'source_url':  'https://github.com/khildren/communityplaylist',
        'tags':        ['django', 'music', 'social', 'platform'],
    },
    {
        'slug':        'lostsignal',
        'name':        'Lost Signal',
        'type':        'web',
        'icon':        'fa-signal-stream',
        'color':       '#e879f9',
        'description': 'Music label and artist platform.',
        'status':      'wip',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/lostsignal',
        'tags':        ['music', 'label'],
    },
    {
        'slug':        'apothecary',
        'name':        'Apothecary',
        'type':        'web',
        'icon':        'fa-mortar-pestle',
        'color':       '#34d399',
        'description': '',
        'status':      'wip',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/apothecary',
        'tags':        [],
    },
    {
        'slug':        'bluesolutions',
        'name':        'Blue Solutions',
        'type':        'web',
        'icon':        'fa-droplet',
        'color':       '#38bdf8',
        'description': 'Blue Solutions business site.',
        'status':      'live',
        'platform':    'Web',
        'live_url':    'https://bluesolutions.biz',
        'source_url':  'https://github.com/khildren/bluesolutions',
        'tags':        ['wordpress', 'business'],
    },
    {
        'slug':        'epk',
        'name':        'EPK',
        'type':        'web',
        'icon':        'fa-id-card',
        'color':       '#a78bfa',
        'description': 'Electronic Press Kit.',
        'status':      'wip',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/epk',
        'tags':        ['music', 'press', 'portfolio'],
    },
    {
        'slug':        'portfolio-blue',
        'name':        'Portfolio Blue',
        'type':        'web',
        'icon':        'fa-briefcase',
        'color':       '#60a5fa',
        'description': 'Portfolio site.',
        'status':      'wip',
        'platform':    'Web',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/portfolio-blue',
        'tags':        ['portfolio'],
    },
    {
        'slug':        'seedling-society',
        'name':        'Seedling Society',
        'type':        'web',
        'icon':        'fa-seedling',
        'color':       '#86efac',
        'description': 'Seedling Society marketplace and community platform.',
        'status':      'wip',
        'platform':    'Web',
        'live_url':    'https://seedlingsociety.com',
        'source_url':  'https://github.com/khildren/seedling-society-market',
        'tags':        ['marketplace', 'community', 'e-commerce'],
    },

    # ── Infra / Tools ─────────────────────────────────────────────────────────

    {
        'slug':        'sapiens',
        'name':        'Sapiens',
        'type':        'infra',
        'icon':        'fa-city',
        'color':       '#fbbf24',
        'description': 'Sapiens city-builder game server in Docker on Unraid. Custom container conversion from the official Linux build — good template for hosting indie game servers for small businesses, families, or community groups.',
        'status':      'live',
        'platform':    'Unraid Docker',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/docker-sapiens',
        'tags':        ['docker', 'game', 'unraid', 'small-biz', 'template'],
    },
    {
        'slug':        'lidarr-mv-sync',
        'name':        'Lidarr MV Sync',
        'type':        'infra',
        'icon':        'fa-film',
        'color':       '#f472b6',
        'description': 'Syncs Lidarr music library with music video files. Watches for new Lidarr downloads and auto-organizes music video counterparts into Plex-compatible folders.',
        'status':      'live',
        'platform':    'Unraid / Plex',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/mv-lidarr-addon',
        'tags':        ['plex', 'lidarr', 'unraid', 'music', 'automation'],
    },
    {
        'slug':        'cp-worker',
        'name':        'CP Worker',
        'type':        'infra',
        'icon':        'fa-gears',
        'color':       '#f97316',
        'description': 'CommunityPlaylist background worker. Handles async processing jobs for the CP platform. Runs as a Docker container on Unraid.',
        'status':      'live',
        'platform':    'Unraid Docker',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/cp-worker',
        'tags':        ['docker', 'unraid', 'worker', 'communityplaylist'],
    },
    {
        'slug':        'tokyo7-admin-api',
        'name':        'Tokyo7 Admin API',
        'type':        'infra',
        'icon':        'fa-server',
        'color':       '#2dd4bf',
        'description': 'Admin and automation API for the Tokyo7 server infrastructure. Handles remote management tasks and scripted operations.',
        'status':      'live',
        'platform':    'Unraid',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/tokyo7-admin-api',
        'tags':        ['api', 'admin', 'unraid', 'server', 'automation'],
    },

    # ── Utility / Bots ────────────────────────────────────────────────────────

    {
        'slug':        'discord-bot',
        'name':        'Discord Bot',
        'type':        'utility',
        'icon':        'fa-robot',
        'color':       '#818cf8',
        'description': 'Discord bot running in Docker on Unraid.',
        'status':      'live',
        'platform':    'Unraid Docker',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/discord-bot',
        'tags':        ['discord', 'bot', 'docker', 'unraid'],
    },
    {
        'slug':        'tokyo7-discord-bot',
        'name':        'Tokyo7 Discord Bot',
        'type':        'utility',
        'icon':        'fa-robot',
        'color':       '#2dd4bf',
        'description': 'Discord bot for the Tokyo7 server community.',
        'status':      'live',
        'platform':    'Unraid',
        'live_url':    '',
        'source_url':  'https://github.com/khildren/tokyo7-discord-bot',
        'tags':        ['discord', 'bot', 'tokyo7'],
    },
    {
        'slug':        'sms-autoreplier',
        'name':        'SMS AutoReplier',
        'type':        'utility',
        'icon':        'fa-message-dots',
        'color':       '#7c6af7',
        'description': 'Native Android background service — watches incoming SMS for keyword patterns and fires a configurable auto-reply in milliseconds. Built for on-call shift claiming.',
        'status':      'beta',
        'platform':    'Android',
        'live_url':    'https://expo.hihilabs.xyz',
        'source_url':  'https://expo.hihilabs.xyz/sms-autoreplier-src.tar',
        'tags':        ['android', 'kotlin', 'sms', 'automation'],
    },
]
