# Generated by Django 5.2.14 on 2026-05-29 20:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount_cents', models.IntegerField()),
                ('due_day', models.IntegerField(help_text='Day of month (1–31)')),
                ('category', models.CharField(choices=[('housing', 'Housing'), ('utilities', 'Utilities'), ('subscriptions', 'Subscriptions'), ('insurance', 'Insurance'), ('debt', 'Debt'), ('family', 'Family'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=20)),
                ('is_auto_pay', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence_rule_id', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pepperjuice_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_day', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField(default=datetime.date.today)),
                ('amount_cents', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pepperjuice.bill')),
            ],
            options={
                'ordering': ['-paid_date'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goal_type', models.CharField(choices=[('college', 'College Fund'), ('parent_loan', 'Parent Loan Payoff'), ('emergency', 'Emergency Fund'), ('investment', 'Investment'), ('vacation', 'Vacation'), ('other', 'Other')], default='other', max_length=20)),
                ('target_cents', models.BigIntegerField()),
                ('current_cents', models.BigIntegerField(default=0)),
                ('monthly_contribution_cents', models.IntegerField(default=0)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('sequence_account_id', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SequenceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CachedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('pod', 'Pod'), ('income', 'Income Source'), ('external', 'External')], default='pod', max_length=20)),
                ('balance_cents', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_business', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='pepperjuice.sequenceconnection')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('connection', 'sequence_id')},
            },
        ),
    ]
