# Generated by Django 5.2.14 on 2026-05-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperjuice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedaccount',
            name='account_subtype',
            field=models.CharField(choices=[('cash', 'Cash / Checking / Savings'), ('investment', 'Investment / Retirement'), ('loan', 'Loan'), ('credit', 'Credit Card'), ('crypto', 'Crypto'), ('bucket', 'Budget Bucket'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='cachedaccount',
            name='institution',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
