# Generated by Django 5.2.13 on 2026-05-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='key',
            field=models.CharField(blank=True, choices=[('', '—'), ('C', 'C'), ('Cm', 'Cm'), ('C#', 'C#'), ('C#m', 'C#m'), ('D', 'D'), ('Dm', 'Dm'), ('Eb', 'Eb'), ('Ebm', 'Ebm'), ('E', 'E'), ('Em', 'Em'), ('F', 'F'), ('Fm', 'Fm'), ('F#', 'F#'), ('F#m', 'F#m'), ('G', 'G'), ('Gm', 'Gm'), ('Ab', 'Ab'), ('Abm', 'Abm'), ('A', 'A'), ('Am', 'Am'), ('Bb', 'Bb'), ('Bbm', 'Bbm'), ('B', 'B'), ('Bm', 'Bm')], max_length=4),
        ),
    ]
