# Generated by Django 5.2.15 on 2026-06-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_contact_portal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pricing_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Pricing multiplier for this client (org size / strategic value). 1.0 = baseline.', max_digits=5),
        ),
    ]
